services:
  auth:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["./server"]
    restart: always
    ports: 
      - '8080:8080'
    networks:
      - api
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api

volumes:
  postgres_data:

networks:
  api:
    driver: bridge